name: Test2

on:
  pull_request_target:
    branches: [main]
    types: [opened, synchronize, reopened, closed]
    paths:
      - "posts/**"

  workflow_dispatch:
    inputs:
      pr_number:
        description: "The number of the pull request to create preview for"
        required: true
        type: number

jobs:
  test2:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install PyGithub

      - name: Run script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python -u test2.py